apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi-admin
  template:
    metadata:
      labels:
        app: medi-admin
    spec:
      imagePullSecrets:
        - name: medi-regcred
      containers:
        - name: medi-admin
          image: suryamurala369/medi-admin:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://medi-backend-service:5000"
