apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi-admin
  template:
    metadata:
      labels:
        app: medi-admin
    spec:
      containers:
        - name: medi-admin
          image: docker.io/suryamurala369/medi-admin:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: medi-admin-service
spec:
  selector:
    app: medi-admin
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
