apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi-backend
  template:
    metadata:
      labels:
        app: medi-backend
    spec:
      imagePullSecrets:
        - name: medi-regcred
      containers:
        - name: medi-backend
          image: docker.io/suryamurala369/medi-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: medi-backend-secrets
