apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi-client
  template:
    metadata:
      labels:
        app: medi-client
    spec:
      containers:
        - name: medi-client
          image: docker.io/suryamurala369/medi-client:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://medi-backend-service:5000"
            - name: REACT_APP_RAZORPAY_KEY_ID
              value: "rzp_test_vMJzshzmGap5FC"
            - name: REACT_APP_GOOGLE_CLIENT_ID
              value: "939406997619-dg4q1c1vhhs3nj8apl2sdf8kdkfi2u63.apps.googleusercontent.com"
            - name: PORT
              value: "3000"
