apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi-client
  template:
    metadata:
      labels:
        app: medi-client
    spec:
      imagePullSecrets:
        - name: medi-regcred
      containers:
        - name: medi-client
          image: suryamurala369/medi-client:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://medi-backend-service:5000"
