apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi-client
  template:
    metadata:
      labels:
        app: medi-client
    spec:
      containers:
        - name: medi-client
          image: docker.io/suryamurala369/medi-client:latest
          ports:
            - containerPort: 80
